models/product.py
from sqlalchemy import *
from extentions import db


class Product(db.Model):
    __tablename__ = "products"
    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False, index=True)
    description = Column(String, nullable=False, index=True)
    price = Column(Integer, nullable=False, index=True)
    status = Column(Integer, nullable=False, index=True)

blueprints/general.py
from flask import Blueprint, render_template, request

from models.product import Product

app = Blueprint("general", __name__)


@app.route('/')
def main():
    search = request.args.get('search', None)

    products = Product.query.filter(Product.status == 1)

    if search is not None:
        products = products.filter(Product.name.like(f'%{search}%'))

    products = products.all()

    return render_template("main.html", products=products, search=search)


@app.route('/product/<int:id>/<name>')
def product(id, name):
    product = Product.query.filter(Product.id == id).filter(Product.name == name).filter(
        Product.status == 1).first_or_404()
    return render_template('product.html', product=product)


@app.route('/about')
def about():
    return render_template("about.html")

blueprints/product.py
from flask import Blueprint
import models.product

app = Blueprint("product", __name__)


@app.route('/product')
def product():  # put application's code here
    return 'this is product page'

templates/part/header.html
<header>
    <img style="width: 350px" src="{{ url_for('static',filename = 'image/logopurpletxt2.png') }}"
         alt="MFK online-shop">
    <section>

        <a href="#">Main page</a>
        <a href="#">Special offers</a>
        <a href="#">New products</a>
        <a href="#">About us</a>

        <form action="/" method="get">
                <input type="search" name="search" value="{{ search if search != None }}" placeholder="Search...">
        </form>

    </section>
</header>

templates/part/product.html
<section class="product-box">
    <img src="{{ url_for('static',filename='cover/'+p.id|string+'.jpg') }}">
    <span class="tag"><img src="{{ url_for('static', filename="image/icons/delivery.png") }}"> free delivery</span>
    <span class="tag"><img src="{{ url_for('static', filename="image/icons/check.png") }}"> Guarantee</span>

    <h3>{{ p.name }}</h3>
    <p>{{ p.description|truncate(50) }}</p>
    <a href="{{ url_for('general.product', id=p.id, name=p.name) }}">More... <img
            src="{{ url_for('static', filename="image/icons/cart.png") }}"></a>

</section>