models/cart.py
from sqlalchemy import *
from sqlalchemy.orm import backref

from extentions import db


class Cart(db.Model):
    __tablename__ = "carts"
    id = Column(Integer, primary_key=True)
    status = Column(String, default="pending")
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    user = db.relationship("User", backref=backref('carts', lazy='dynamic'))

    def total_price(self):
        total = 0
        for item in self.cart_items:
            t = item.price * item.quantity
            total += t
        return total

    def get_status_english(self):
        if self.status == 'pending':
            return "waiting for purchase"

        if self.status == 'purchased':
            return "purchased"

        if self.status == 'sent':
            return "sent"

        if self.status == 'rejected':
            return "rejected"

models/user.py
from sqlalchemy import *
from extentions import db, get_current_time
from flask_login import UserMixin
from flask_login import login_manager


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False, index=True)
    password = Column(String, nullable=False, index=True)
    name = Column(String, nullable=False, index=True)
    lastName = Column(String, nullable=False, index=True)
    phone = Column(String, unique=True, nullable=False, index=True)
    email = Column(String, unique=True, nullable=False, index=True)
    address = Column(String, nullable=True, index=True)
    date_created = Column(String(15), default=get_current_time)

blueprints/user.py
from flask import Blueprint, render_template, flash, url_for, request, redirect
from flask_login import login_user, login_required, current_user
from passlib.hash import sha256_crypt
import requests
from models.cart import Cart
from models.cart_item import CartItem
from models.payment import Payment
from models.product import Product
from models.user import User
from extentions import db
import config
import models.user

app = Blueprint("user", __name__)


@app.route('/user/login/signup', methods=['GET', 'POST'])
def user_signup():
    if request.method == 'GET':
        return render_template("user/signup.html")
    else:
        register = request.form.get('register', None)
        username = request.form.get('username', None)
        name = request.form.get('name', None)
        lastName = request.form.get('lastName', None)
        phone = request.form.get('phone', None)
        email = request.form.get('email', None)
        address = request.form.get('address', None)
        password = request.form.get('password', None)

        user = User.query.filter(User.username == username).first()
        if user is not None:
            flash('sorry this username is already taken by another person')
            return redirect(url_for('user.user_signup'))
        if register is not None:
            user = User(username=username, password=sha256_crypt.encrypt(password), name=name,
                        lastName=lastName, phone=phone, email=email,address=address)
            db.session.add(user)
            db.session.commit()
            login_user(user)
            return redirect(url_for('user.user_login'))


@app.route('/user/login', methods=['GET', 'POST'])
def user_login():
    if request.method == "POST":
        username = request.form.get('username', None)
        password = request.form.get('password', None)
        user = User.query.filter(User.username == username).first()
        if user is not None and sha256_crypt.verify(password, user.password) is True:
            login_user(user)
            return redirect(url_for('user.dashboard'))
        else:
            flash('invalid username or password')
            return redirect(url_for("user.user_login"))
    else:
        return render_template("user/login.html")


@app.route('/add-to-cart', methods=["GET"])
@login_required
def add_to_cart():
    quantity = request.args.get('quantity')
    id = request.args.get('id')
    product = Product.query.filter(Product.id == id).first_or_404()

    cart = current_user.carts.filter(Cart.status == 'pending').first()
    if cart is None:
        cart = Cart()
        current_user.carts.append(cart)
        db.session.add(cart)

    cart_item = cart.cart_items.filter(CartItem.product == product).first()
    if cart_item is None:
        item = CartItem(quantity=quantity)
        item.price = product.price
        item.cart = cart
        item.product = product
        db.session.add(item)
    else:
        cart_item.quantity += quantity

    db.session.commit()

    return redirect(url_for('user.cart'))


@app.route('/remove-from-cart', methods=["GET"])
@login_required
def remove_from_cart():
    id = request.args.get('id')
    cart_item = CartItem.query.filter(CartItem.id == id).first_or_404()
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
    else:
        db.session.delete(cart_item)

    db.session.commit()
    return redirect(url_for('user.cart'))


@app.route('/cart', methods=["GET"])
@login_required
def cart():
    cart = current_user.carts.filter(Cart.status == "pending").first()
    return render_template("/user/cart.html", cart=cart)


@app.route('/payment', methods=["GET"])
@login_required
def payment():
    cart = current_user.carts.filter(Cart.status == 'pending').first()

    r = requests.post(config.PAYMENT_FIRST_REQUEST_URL,
                      data={
                          'api': config.PAYMENT_MERCHANT,
                          'amount': cart.total_price(),
                          'callback': config.PAYMENT_CALLBACK,
                      })
    token = r.json()['result']['token']
    url = r.json()['result']['url']

    pay = Payment(price=cart.total_price(), token=token)
    pay.cart = cart
    db.session.add(pay)
    db.session.commit()

    return redirect(url)


@app.route('/verify', methods=["GET"])
@login_required
def verify():
    token = request.args.get('token')
    pay = Payment.query.filter(Payment.token == token).first_or_404()

    r = requests.post(config.PAYMENT_VERIFY_REQUEST_URL,
                      data={
                          'api': 'sandbox',
                          'amount': pay.price,
                          'token': token
                      })

    pay_status = bool(r.json()['success'])

    if pay_status:
        transaction_id = r.json()['result']['transaction_id']
        refid = r.json()['result']['refid']
        card_pan = r.json()['result']['card_pan']

        pay.card_pan = card_pan
        pay.transaction_id = transaction_id
        pay.refid = refid
        pay.status = 'success'
        pay.cart.status = 'purchased'
        flash('payment was successful')
    else:
        flash('payment was not successful')
        pay.status = 'failed'

    db.session.commit()

    return redirect(url_for('user.dashboard'))


@app.route('/user/dashboard', methods=["GET"])
@login_required
def dashboard():
        return render_template("/user/dashboard.html")


@app.route('/user/dashboard/order/<id>', methods=["GET"])
@login_required
def order(id):
    cart = current_user.carts.filter(Cart.id == id).first_or_404()
    return render_template("/user/order.html", cart=cart)

templates/user/cart.html
{% extends 'base.html' %}
{% block header %}
    <title>Your Shopping Cart</title>
{% endblock %}
{% block body %}

    {% if cart != None and cart.cart_items|list|length > 0 %}

        {% for cart_item in cart.cart_items %}
            {{ cart_item.product.name }} ----- {{ cart_item.quantity }} ----- {{ cart_item.product.price }}<br>
            <form action="/remove-from-cart" method="get">
                <input type="hidden" name="id" value="{{ cart_item.id }}">
                <input type="submit" value="remove product">
            </form>
        {% endfor %}


        <b>Total Price: -{{ cart.total_price() }}- Dollar</b>


        <a href="/payment">Purchase</a>

    {% else %}
        your shopping cart is empty
    {% endif %}
{% endblock %}

templates/user/dashboard.html
{% extends 'base.html' %}
{% block header %}
    <title>user dashboard</title>
{% endblock %}
{% block body %}

    {% for cart in current_user.carts|selectattr('status','!=','pending') %}
    <a href="{{ url_for('user.order', id=cart.id) }}">{{ cart.status }} - {{ cart.id }}</a><br>
    {% endfor %}

{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% block header %}
    <title>User Login</title>
{% endblock %}
{% block body %}

    <h1>User Login</h1>
    <form action="#" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="text" name="username" placeholder="username"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit">
        <a href="/user/login/signup">Sign-Up</a>
    </form>

    {% for m in get_flashed_messages() %}
        {{ m }}
    {% endfor %}

{% endblock %}

templates/user/order.html
{% extends 'base.html' %}
{% block header %}
    <title>Your Order</title>
{% endblock %}
{% block body %}


    {{ cart.status }}<br>
    {% for item in cart.cart_items %}
        {{ item.product.name }} - {{ item.price }}<br>
    {% endfor %}

{% endblock %}

templates/user/signup.html
{% extends 'base.html' %}
{% block header %}
    <title>User Sign-Up</title>
{% endblock %}
{% block body %}

    <h1>User Sign-Up</h1>
    <form action="#" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="register" value="1">
        <input type="text" name="username" placeholder="username"><br>
        <input type="text" name="name" placeholder="first name"><br>
        <input type="text" name="lastName" placeholder="last name"><br>
        <input type="text" name="phone" placeholder="mobile number"><br>
        <input type="text" name="email" placeholder="email"><br>
        <input type="text" name="address" placeholder="address"><br>
        <input type="password" name="password" placeholder="password"><br>
        <input type="submit">
        <a href="/user/login">login</a>
    </form>
    {% for n in get_flashed_messages() %}
        {{ n }}
    {% endfor %}


{% endblock %}